on: pull_request
env:
  GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
  GIT_HEAD_SHA: ${{ github.event.pull_request.head.sha }}

  concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: PNPM install
        uses: ./.github/actions/setup/pnpm/install

      - name: Verify Lint
        run: |
          pnpm nx affected --base=origin/$GIT_BASE_BRANCH --head=$GIT_HEAD_SHA -t lint --parallel=3

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: PNPM install
        uses: ./.github/actions/setup/pnpm/install

      - name: Verify Unit Test
        run: |
          pnpm nx affected --base=origin/$GIT_BASE_BRANCH --head=$GIT_HEAD_SHA -t test --parallel=3 --configuration=ci

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: PNPM install
        uses: ./.github/actions/setup/pnpm/install

      - name: Verify Build
        run: |
          pnpm nx affected --base=origin/$GIT_BASE_BRANCH --head=$GIT_HEAD_SHA -t build --parallel=3
  affected:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: uploadAffected
        uses: ./.github/actions/affected/write
        with:
          artifact_path: "${{ github.workspace }}/env"
